<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Version>0.5.3</Version>
    <RuntimeFrameworkVersion>8.0.31</RuntimeFrameworkVersion>
    <AssemblyName>Flashback</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/Flashback.ico</ApplicationIcon>
    <RestorePackagesPath>../.packages</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <Resource Include="Assets/Flashback.ico" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>
</Project>









